on: push

permissions:
  id-token: write
  contents: read
  actions: read

env:
  REGION: ap-southeast-1

jobs:
  build:
    name: Run my self-hosted runner
    runs-on: ['self-hosted', 'linux', 'x64', 'ubuntu-2204', 'medium-instance']

    steps:
      - uses: actions/checkout@v3
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Get list of rules
        shell: pwsh
        run: |
          Get-ScriptAnalyzerRule
