on: push

jobs:
  build:
    name: Run my self-hosted runner
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Test self-hosted runner run on aws..."
          TAG=$GITHUB_REF_NAME
          echo $TAG